Java3course/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path(r'catalog/', include(('goods_manager.urls', 'goods_manager'), namespace='catalog')),
    path(r'shop/', include(('shop_manager.urls', 'shop_manager'), namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(path(r'', include(('main_app.urls', 'main_app'), namespace='main')))

authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from authentication.views import UserRegistrationView, UserProfileView

urlpatterns = [
    url(r'login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    url(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'registration/', UserRegistrationView.as_view(), name='registration'),
    url(r'profile/', UserProfileView.as_view(), name='profile'),
]

main_app/urls.py
from django.conf.urls import url

from main_app import views

urlpatterns = [
    url(r'', views.MainView.as_view(), name='main_page'),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    is_editor = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)

    def get_user_types_repr(self):
        if not self.is_editor and not self.is_manager:
            return 'Simple user'
        elif self.is_editor and not self.is_manager:
            return 'Editor user'
        elif not self.is_editor and self.is_manager:
            return 'Manager user'
        elif self.is_editor and self.is_manager:
            return 'Editor and manager user'

authentication/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()

authentication/views.py
from django.contrib.auth import login, get_user_model
from django.shortcuts import redirect
from rest_framework.compat import authenticate
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from authentication.forms import UserCreationForm
from main_app.utils import ApplyMethodTemplate
from shop_manager.models import Shop

User = get_user_model()


class UserRegistrationView(APIView):

    def get(self, request):
        form = UserCreationForm()
        data = {
            'form': form,
        }
        return Response(data=data, template_name='authentication/registration.html')

    def post(self, request, *args, **kwargs):
        user_form = UserCreationForm(request.data)
        if user_form.is_valid():
            user_form.save()
            user = authenticate(username=request.data['username'], password=request.data['password2'])
            login(request, user)
            return redirect('/')
        data = {
            'form': user_form,
        }
        return Response(data=data, template_name='authentication/registration.html')


class UserProfileView(GenericAPIView):

    permission_classes = (IsAuthenticated, )

    def get_object(self):
        return self.request.user

    @ApplyMethodTemplate('authentication/profile.html')
    def get(self, request, *args, **kwargs):
        user = self.get_object()
        response_data = {
            'request': request,
            'user': user,
            'user_type': user.get_user_types_repr(),
            'shops': Shop.objects.filter(owner=request.user),
        }
        return Response(data=response_data)

authentication/templates/authentication/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'authentication/style.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body class="container">
{% block content %}{% endblock %}
</body>
</html>

authentication/templates/authentication/login.html
{% extends "authentication/base.html" %}
{% block content %}
<div class="card col-sm-5 col-sm-offset-4 auth-form">
    <div class="card-body">
        <h2 class="card-title">Login</h2>
        <form method="post" class="">
            {% csrf_token %}
            <div class="row auth-input">
                <div class="col-sm-5">Username:</div>
                <div class="col-sm-7">{{ form.username }}</div>
            </div>
            <div class="row auth-input">
                <div class="col-sm-5">Password:</div>
                <div class="col-sm-7">{{ form.password }}</div>
            </div>
            <button type="submit" class="btn btn-primary auth-button">Login</button>
            <p>If you are not registered, please
                <a href="/auth/registration/"> sign up</a>
            </p>
            <a href="/">Go home</a>
        </form>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/profile.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/style.css' %}">
<div class="row">
<div class="col-sm-2 col-sm-offset-5 profile-header-block">
<h4>Profile</h4>
</div>
</div>
<div class="row row-eq-height">
<div class="col-sm-5 profile-info-block">
<p>Username: <i>{{ user.username }}</i></p>
<p>Email: <i>{{ user.email }}</i></p>
<p>You are: <i>{{ user_type }}</i></p>
<a href="{% url 'auth:logout' %}">
<button class="btn btn-danger">Logout</button>
</a>
</div>
{% if user.is_manager %}
    <div class="col-sm-7 shops-management-list-block">
        {% for shop in shops %}
        <p>Go to <a href="/shop/{{ shop.pk }}/">{{ shop.name }}</a> management</p>
        {% endfor %}
    </div>
{% endif %}
</div>
{% endblock %}

authentication/templates/authentication/registration.html
{% extends "authentication/base.html" %}
{% block content %}
<div class="card col-sm-5 col-sm-offset-4 auth-form">
    <div class="card-body">
        <h2 class="card-title">Sign up</h2>
        <form method="post">
            {% csrf_token %}
            <div class="row auth-input">
                <div class="col-sm-5">Username:</div>
                <div class="col-sm-7">{{ form.username }}</div>
            </div>
            <div class="row auth-input">
                <div class="col-sm-5">Password:</div>
                <div class="col-sm-7">{{ form.password1 }}</div>
            </div>
            <div class="row auth-input">
                <div class="col-sm-5">Confirm password:</div>
                <div class="col-sm-7">{{ form.password2 }}</div>
            </div>
            {% for _, error in form.errors.items %}
            <p class="error-note">{{error}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary auth-button">Sign up</button>
            <a href="/">Go home</a>
        </form>
   </div>
</div>
{% endblock %}

authentication/templates/authentication/stub.html
{% extends "base/base.html" %}
{% block content %}
{{ user.username }}
{% endblock %}