Java3course/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path(r'catalog/', include(('goods_manager.urls', 'goods_manager'), namespace='catalog')),
    path(r'shop/', include(('shop_manager.urls', 'shop_manager'), namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(path(r'', include(('main_app.urls', 'main_app'), namespace='main')))

authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from authentication.views import UserRegistrationView, UserProfileView

urlpatterns = [
    url(r'login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    url(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'registration/', UserRegistrationView.as_view(), name='registration'),
    url(r'profile/', UserProfileView.as_view(), name='profile'),
]

main_app/urls.py
from django.conf.urls import url

from main_app import views

urlpatterns = [
    url(r'', views.MainView.as_view(), name='main_page'),
]

main_app/models.py
from django.db import models


class AdditionalAbstractModelImage(models.Model):

    class Meta:
        abstract = True

    photo = models.ImageField()

main_app/views.py
from django.views.generic import TemplateView


class MainView(TemplateView):
    template_name = 'base/base.html'

main_app/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body class="container">
<nav class="row header row-vertical-align">
<div class="col-sm-10">
    <a class="nav-link" href="/catalog/">
        <div class="col-sm-1 link-block" align="center">
            Shop
        </div>
    </a>
    <a class="nav-link" href="/blog/">
        <div class="col-sm-1 link-block" align="center">
            Blog
        </div>
    </a>
</div>
    {% if not request.user.is_anonymous %}
    <div class="col-sm-2 bucket-link" align="right">
        <p><a href="/catalog/bucket/">Bucket&nbsp<span class="glyphicon glyphicon-shopping-cart"></span></a></p>
    </div>
    {% endif %}
</nav>
<div class="row sub-nav">
    <div class="col-sm-3">
        Here must be logo
    </div>
    <div class="col-sm-6">
        <form class="input-group" method="get" action="/catalog/search/">
            <input type="text" class="form-control" placeholder="Search" name="request_line">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
         </form>
    </div>
    <div class="col-sm-3">
        {% if request.user.is_anonymous %}
            <a href="{% url 'auth:login' %}">
                <button class="btn btn-secondary auth-button">Sign in</button>
            </a>
        {% else %}
            <h4>
                <a href="/auth/profile/">Hi, {{ request.user.username }}</a>
            </h4>
        {% endif %}
    </div>
</div>
<div>
    {% block content %}{% endblock %}
</div>
</body>
</html>